server:
  port:
    8080
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE